include:
  - local: /.gitlab/security-ci.yml
  - local: /.gitlab/secret-ci.yml
  - local: /.gitlab/tag-ci.yml
  - local: /.gitlab/publish-ci.yml
  - local: /.gitlab/release-ci.yml
stages:
  - test
  - tag
  - publish
  - release

security:
  extends: .security
secret:
  extends: .secret
shell-linter:
  stage: test
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  image: alpine
  variables:
    SHELLCHECK_VERSION: "0.10.0"
  before_script:
    - |
      apk add bash
      (cd /usr/local/bin; wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz -O- | tar --strip-components 1 -xJvf - shellcheck-v$SHELLCHECK_VERSION/shellcheck)
      shellcheck -V
  script:
    - 'shellcheck compose-systemd'

.tag_base:
  extends: .tag
  needs:
    - security
    - secret
    - shell-linter
tag:major:
  extends: .tag_base
tag:minor:
  extends: .tag_base
tag:patch:
  extends: .tag_base

publish:
  extends: .publish
gitlab-release:
  extends: .release
  needs:
    - job: publish
      artifacts: true
